# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.episode_short_detail import EpisodeShortDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestEpisodeShortDetail(unittest.TestCase):
    """EpisodeShortDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpisodeShortDetail(self):
        """Test EpisodeShortDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.episode_short_detail.EpisodeShortDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
