# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.top250_data_detail import Top250DataDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestTop250DataDetail(unittest.TestCase):
    """Top250DataDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTop250DataDetail(self):
        """Test Top250DataDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.top250_data_detail.Top250DataDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
