# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.box_office_all_time_data_detail import BoxOfficeAllTimeDataDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestBoxOfficeAllTimeDataDetail(unittest.TestCase):
    """BoxOfficeAllTimeDataDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBoxOfficeAllTimeDataDetail(self):
        """Test BoxOfficeAllTimeDataDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.box_office_all_time_data_detail.BoxOfficeAllTimeDataDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
