# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.movies_api_api import MoviesApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMoviesApiApi(unittest.TestCase):
    """MoviesApiApi unit test stubs"""

    def setUp(self):
        self.api = MoviesApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_a_pi_awards_api_key_id_get(self):
        """Test case for a_pi_awards_api_key_id_get

        """
        pass

    def test_a_pi_box_office_all_time_api_key_get(self):
        """Test case for a_pi_box_office_all_time_api_key_get

        """
        pass

    def test_a_pi_box_office_api_key_get(self):
        """Test case for a_pi_box_office_api_key_get

        """
        pass

    def test_a_pi_coming_soon_api_key_get(self):
        """Test case for a_pi_coming_soon_api_key_get

        """
        pass

    def test_a_pi_company_api_key_id_get(self):
        """Test case for a_pi_company_api_key_id_get

        """
        pass

    def test_a_pi_external_sites_api_key_id_get(self):
        """Test case for a_pi_external_sites_api_key_id_get

        """
        pass

    def test_a_pi_full_cast_api_key_id_get(self):
        """Test case for a_pi_full_cast_api_key_id_get

        """
        pass

    def test_a_pi_images_api_key_id_get(self):
        """Test case for a_pi_images_api_key_id_get

        """
        pass

    def test_a_pi_images_api_key_id_options_get(self):
        """Test case for a_pi_images_api_key_id_options_get

        """
        pass

    def test_a_pi_in_theaters_api_key_get(self):
        """Test case for a_pi_in_theaters_api_key_get

        """
        pass

    def test_a_pi_keyword_api_key_id_get(self):
        """Test case for a_pi_keyword_api_key_id_get

        """
        pass

    def test_a_pi_metacritic_reviews_api_key_id_get(self):
        """Test case for a_pi_metacritic_reviews_api_key_id_get

        """
        pass

    def test_a_pi_most_popular_movies_api_key_get(self):
        """Test case for a_pi_most_popular_movies_api_key_get

        """
        pass

    def test_a_pi_most_popular_t_vs_api_key_get(self):
        """Test case for a_pi_most_popular_t_vs_api_key_get

        """
        pass

    def test_a_pi_name_api_key_id_get(self):
        """Test case for a_pi_name_api_key_id_get

        """
        pass

    def test_a_pi_name_awards_api_key_id_get(self):
        """Test case for a_pi_name_awards_api_key_id_get

        """
        pass

    def test_a_pi_posters_api_key_id_get(self):
        """Test case for a_pi_posters_api_key_id_get

        """
        pass

    def test_a_pi_ratings_api_key_id_get(self):
        """Test case for a_pi_ratings_api_key_id_get

        """
        pass

    def test_a_pi_reviews_api_key_id_get(self):
        """Test case for a_pi_reviews_api_key_id_get

        """
        pass

    def test_a_pi_search_all_api_key_expression_get(self):
        """Test case for a_pi_search_all_api_key_expression_get

        """
        pass

    def test_a_pi_search_api_key_expression_get(self):
        """Test case for a_pi_search_api_key_expression_get

        """
        pass

    def test_a_pi_search_company_api_key_expression_get(self):
        """Test case for a_pi_search_company_api_key_expression_get

        """
        pass

    def test_a_pi_search_episode_api_key_expression_get(self):
        """Test case for a_pi_search_episode_api_key_expression_get

        """
        pass

    def test_a_pi_search_keyword_api_key_expression_get(self):
        """Test case for a_pi_search_keyword_api_key_expression_get

        """
        pass

    def test_a_pi_search_movie_api_key_expression_get(self):
        """Test case for a_pi_search_movie_api_key_expression_get

        """
        pass

    def test_a_pi_search_name_api_key_expression_get(self):
        """Test case for a_pi_search_name_api_key_expression_get

        """
        pass

    def test_a_pi_search_series_api_key_expression_get(self):
        """Test case for a_pi_search_series_api_key_expression_get

        """
        pass

    def test_a_pi_search_title_api_key_expression_get(self):
        """Test case for a_pi_search_title_api_key_expression_get

        """
        pass

    def test_a_pi_season_episodes_api_key_id_season_number_get(self):
        """Test case for a_pi_season_episodes_api_key_id_season_number_get

        """
        pass

    def test_a_pi_top250_movies_api_key_get(self):
        """Test case for a_pi_top250_movies_api_key_get

        """
        pass

    def test_a_pi_top250_t_vs_api_key_get(self):
        """Test case for a_pi_top250_t_vs_api_key_get

        """
        pass

    def test_a_pi_trailer_api_key_id_get(self):
        """Test case for a_pi_trailer_api_key_id_get

        """
        pass

    def test_a_pi_usage_api_key_get(self):
        """Test case for a_pi_usage_api_key_get

        """
        pass

    def test_a_pi_user_ratings_api_key_id_get(self):
        """Test case for a_pi_user_ratings_api_key_id_get

        """
        pass

    def test_a_pi_you_tube_trailer_api_key_id_get(self):
        """Test case for a_pi_you_tube_trailer_api_key_id_get

        """
        pass

    def test_a_pifaq_api_key_id_get(self):
        """Test case for a_pifaq_api_key_id_get

        """
        pass

    def test_a_piim_db_list_api_key_id_get(self):
        """Test case for a_piim_db_list_api_key_id_get

        """
        pass

    def test_lang_api_report_api_key_id_get(self):
        """Test case for lang_api_report_api_key_id_get

        """
        pass

    def test_lang_api_report_api_key_id_options_get(self):
        """Test case for lang_api_report_api_key_id_options_get

        """
        pass

    def test_lang_api_title_api_key_id_get(self):
        """Test case for lang_api_title_api_key_id_get

        """
        pass

    def test_lang_api_title_api_key_id_options_get(self):
        """Test case for lang_api_title_api_key_id_options_get

        """
        pass

    def test_lang_api_wikipedia_api_key_id_get(self):
        """Test case for lang_api_wikipedia_api_key_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
