# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="IMDb-API",
    author_email="",
    url="",
    keywords=["Swagger", "IMDb-API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    The IMDb-API Documentation. You need a &lt;a href&#x3D;&#x27;/Identity/Account/Manage&#x27; target&#x3D;&#x27;_blank&#x27;&gt;&lt;code&gt;API Key&lt;/code&gt;&lt;/a&gt; for testing APIs.&lt;br/&gt;&lt;a class&#x3D;&#x27;link&#x27; href&#x3D;&#x27;/API&#x27;&gt;Back to API Tester&lt;/a&gt;  # noqa: E501
    """
)
