# coding: utf-8

# flake8: noqa
"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.actor_short import ActorShort
from swagger_client.models.award_data import AwardData
from swagger_client.models.award_event import AwardEvent
from swagger_client.models.award_outcome import AwardOutcome
from swagger_client.models.award_outcome_detail import AwardOutcomeDetail
from swagger_client.models.box_office_all_time_data import BoxOfficeAllTimeData
from swagger_client.models.box_office_all_time_data_detail import BoxOfficeAllTimeDataDetail
from swagger_client.models.box_office_short import BoxOfficeShort
from swagger_client.models.box_office_weekend_data import BoxOfficeWeekendData
from swagger_client.models.box_office_weekend_data_detail import BoxOfficeWeekendDataDetail
from swagger_client.models.cast_movie import CastMovie
from swagger_client.models.cast_short import CastShort
from swagger_client.models.cast_short_item import CastShortItem
from swagger_client.models.company_data import CompanyData
from swagger_client.models.company_short import CompanyShort
from swagger_client.models.episode_short_detail import EpisodeShortDetail
from swagger_client.models.external_site_data import ExternalSiteData
from swagger_client.models.external_site_item import ExternalSiteItem
from swagger_client.models.faq_data import FAQData
from swagger_client.models.faq_detail import FAQDetail
from swagger_client.models.full_cast_data import FullCastData
from swagger_client.models.im_db_list_data import IMDbListData
from swagger_client.models.im_db_list_data_detail import IMDbListDataDetail
from swagger_client.models.image_data import ImageData
from swagger_client.models.image_data_detail import ImageDataDetail
from swagger_client.models.key_value_item import KeyValueItem
from swagger_client.models.keyword_data import KeywordData
from swagger_client.models.known_for import KnownFor
from swagger_client.models.language_url import LanguageUrl
from swagger_client.models.metacritic_review_data import MetacriticReviewData
from swagger_client.models.metacritic_review_detail import MetacriticReviewDetail
from swagger_client.models.most_popular_data import MostPopularData
from swagger_client.models.most_popular_data_detail import MostPopularDataDetail
from swagger_client.models.movie_short import MovieShort
from swagger_client.models.name_award_data import NameAwardData
from swagger_client.models.name_award_event import NameAwardEvent
from swagger_client.models.name_award_outcome import NameAwardOutcome
from swagger_client.models.name_award_outcome_detail import NameAwardOutcomeDetail
from swagger_client.models.name_data import NameData
from swagger_client.models.new_movie_data import NewMovieData
from swagger_client.models.new_movie_data_detail import NewMovieDataDetail
from swagger_client.models.poster_data import PosterData
from swagger_client.models.poster_data_item import PosterDataItem
from swagger_client.models.rating_data import RatingData
from swagger_client.models.review_data import ReviewData
from swagger_client.models.review_detail import ReviewDetail
from swagger_client.models.search_data import SearchData
from swagger_client.models.search_result import SearchResult
from swagger_client.models.season_episode_data import SeasonEpisodeData
from swagger_client.models.similar_short import SimilarShort
from swagger_client.models.star_short import StarShort
from swagger_client.models.title_data import TitleData
from swagger_client.models.top250_data import Top250Data
from swagger_client.models.top250_data_detail import Top250DataDetail
from swagger_client.models.trailer_data import TrailerData
from swagger_client.models.tv_episode_info import TvEpisodeInfo
from swagger_client.models.tv_series_info import TvSeriesInfo
from swagger_client.models.usage_data import UsageData
from swagger_client.models.user_rating_data import UserRatingData
from swagger_client.models.user_rating_data_demographic import UserRatingDataDemographic
from swagger_client.models.user_rating_data_demographic_detail import UserRatingDataDemographicDetail
from swagger_client.models.user_rating_data_detail import UserRatingDataDetail
from swagger_client.models.wikipedia_data import WikipediaData
from swagger_client.models.wikipedia_data_plot import WikipediaDataPlot
from swagger_client.models.you_tube_data import YouTubeData
from swagger_client.models.you_tube_data_item import YouTubeDataItem
from swagger_client.models.you_tube_playlist_data import YouTubePlaylistData
from swagger_client.models.you_tube_playlist_data_item import YouTubePlaylistDataItem
from swagger_client.models.you_tube_trailer_data import YouTubeTrailerData
