# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BoxOfficeAllTimeDataDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'rank': 'str',
        'title': 'str',
        'worldwide_lifetime_gross': 'str',
        'domestic_lifetime_gross': 'str',
        'domestic': 'str',
        'foreign_lifetime_gross': 'str',
        'foreign': 'str',
        'year': 'str'
    }

    attribute_map = {
        'id': 'id',
        'rank': 'rank',
        'title': 'title',
        'worldwide_lifetime_gross': 'worldwideLifetimeGross',
        'domestic_lifetime_gross': 'domesticLifetimeGross',
        'domestic': 'domestic',
        'foreign_lifetime_gross': 'foreignLifetimeGross',
        'foreign': 'foreign',
        'year': 'year'
    }

    def __init__(self, id=None, rank=None, title=None, worldwide_lifetime_gross=None, domestic_lifetime_gross=None, domestic=None, foreign_lifetime_gross=None, foreign=None, year=None):  # noqa: E501
        """BoxOfficeAllTimeDataDetail - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._rank = None
        self._title = None
        self._worldwide_lifetime_gross = None
        self._domestic_lifetime_gross = None
        self._domestic = None
        self._foreign_lifetime_gross = None
        self._foreign = None
        self._year = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if rank is not None:
            self.rank = rank
        if title is not None:
            self.title = title
        if worldwide_lifetime_gross is not None:
            self.worldwide_lifetime_gross = worldwide_lifetime_gross
        if domestic_lifetime_gross is not None:
            self.domestic_lifetime_gross = domestic_lifetime_gross
        if domestic is not None:
            self.domestic = domestic
        if foreign_lifetime_gross is not None:
            self.foreign_lifetime_gross = foreign_lifetime_gross
        if foreign is not None:
            self.foreign = foreign
        if year is not None:
            self.year = year

    @property
    def id(self):
        """Gets the id of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The id of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BoxOfficeAllTimeDataDetail.


        :param id: The id of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def rank(self):
        """Gets the rank of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The rank of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """Sets the rank of this BoxOfficeAllTimeDataDetail.


        :param rank: The rank of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._rank = rank

    @property
    def title(self):
        """Gets the title of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The title of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BoxOfficeAllTimeDataDetail.


        :param title: The title of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def worldwide_lifetime_gross(self):
        """Gets the worldwide_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The worldwide_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._worldwide_lifetime_gross

    @worldwide_lifetime_gross.setter
    def worldwide_lifetime_gross(self, worldwide_lifetime_gross):
        """Sets the worldwide_lifetime_gross of this BoxOfficeAllTimeDataDetail.


        :param worldwide_lifetime_gross: The worldwide_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._worldwide_lifetime_gross = worldwide_lifetime_gross

    @property
    def domestic_lifetime_gross(self):
        """Gets the domestic_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The domestic_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._domestic_lifetime_gross

    @domestic_lifetime_gross.setter
    def domestic_lifetime_gross(self, domestic_lifetime_gross):
        """Sets the domestic_lifetime_gross of this BoxOfficeAllTimeDataDetail.


        :param domestic_lifetime_gross: The domestic_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._domestic_lifetime_gross = domestic_lifetime_gross

    @property
    def domestic(self):
        """Gets the domestic of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The domestic of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._domestic

    @domestic.setter
    def domestic(self, domestic):
        """Sets the domestic of this BoxOfficeAllTimeDataDetail.


        :param domestic: The domestic of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._domestic = domestic

    @property
    def foreign_lifetime_gross(self):
        """Gets the foreign_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The foreign_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._foreign_lifetime_gross

    @foreign_lifetime_gross.setter
    def foreign_lifetime_gross(self, foreign_lifetime_gross):
        """Sets the foreign_lifetime_gross of this BoxOfficeAllTimeDataDetail.


        :param foreign_lifetime_gross: The foreign_lifetime_gross of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._foreign_lifetime_gross = foreign_lifetime_gross

    @property
    def foreign(self):
        """Gets the foreign of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The foreign of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._foreign

    @foreign.setter
    def foreign(self, foreign):
        """Sets the foreign of this BoxOfficeAllTimeDataDetail.


        :param foreign: The foreign of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._foreign = foreign

    @property
    def year(self):
        """Gets the year of this BoxOfficeAllTimeDataDetail.  # noqa: E501


        :return: The year of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :rtype: str
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this BoxOfficeAllTimeDataDetail.


        :param year: The year of this BoxOfficeAllTimeDataDetail.  # noqa: E501
        :type: str
        """

        self._year = year

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BoxOfficeAllTimeDataDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BoxOfficeAllTimeDataDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
