# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CastMovie(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'role': 'str',
        'title': 'str',
        'year': 'str',
        'description': 'str'
    }

    attribute_map = {
        'id': 'id',
        'role': 'role',
        'title': 'title',
        'year': 'year',
        'description': 'description'
    }

    def __init__(self, id=None, role=None, title=None, year=None, description=None):  # noqa: E501
        """CastMovie - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._role = None
        self._title = None
        self._year = None
        self._description = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if role is not None:
            self.role = role
        if title is not None:
            self.title = title
        if year is not None:
            self.year = year
        if description is not None:
            self.description = description

    @property
    def id(self):
        """Gets the id of this CastMovie.  # noqa: E501


        :return: The id of this CastMovie.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CastMovie.


        :param id: The id of this CastMovie.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def role(self):
        """Gets the role of this CastMovie.  # noqa: E501


        :return: The role of this CastMovie.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this CastMovie.


        :param role: The role of this CastMovie.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def title(self):
        """Gets the title of this CastMovie.  # noqa: E501


        :return: The title of this CastMovie.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CastMovie.


        :param title: The title of this CastMovie.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def year(self):
        """Gets the year of this CastMovie.  # noqa: E501


        :return: The year of this CastMovie.  # noqa: E501
        :rtype: str
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this CastMovie.


        :param year: The year of this CastMovie.  # noqa: E501
        :type: str
        """

        self._year = year

    @property
    def description(self):
        """Gets the description of this CastMovie.  # noqa: E501


        :return: The description of this CastMovie.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CastMovie.


        :param description: The description of this CastMovie.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CastMovie, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CastMovie):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
