# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeywordData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'keyword': 'str',
        'items': 'list[MovieShort]',
        'error_message': 'str'
    }

    attribute_map = {
        'keyword': 'keyword',
        'items': 'items',
        'error_message': 'errorMessage'
    }

    def __init__(self, keyword=None, items=None, error_message=None):  # noqa: E501
        """KeywordData - a model defined in Swagger"""  # noqa: E501
        self._keyword = None
        self._items = None
        self._error_message = None
        self.discriminator = None
        if keyword is not None:
            self.keyword = keyword
        if items is not None:
            self.items = items
        if error_message is not None:
            self.error_message = error_message

    @property
    def keyword(self):
        """Gets the keyword of this KeywordData.  # noqa: E501


        :return: The keyword of this KeywordData.  # noqa: E501
        :rtype: str
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this KeywordData.


        :param keyword: The keyword of this KeywordData.  # noqa: E501
        :type: str
        """

        self._keyword = keyword

    @property
    def items(self):
        """Gets the items of this KeywordData.  # noqa: E501


        :return: The items of this KeywordData.  # noqa: E501
        :rtype: list[MovieShort]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this KeywordData.


        :param items: The items of this KeywordData.  # noqa: E501
        :type: list[MovieShort]
        """

        self._items = items

    @property
    def error_message(self):
        """Gets the error_message of this KeywordData.  # noqa: E501


        :return: The error_message of this KeywordData.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this KeywordData.


        :param error_message: The error_message of this KeywordData.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeywordData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeywordData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
