# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NameAwardData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'im_db_id': 'str',
        'name': 'str',
        'description': 'str',
        'items': 'list[NameAwardEvent]',
        'name_awards_html': 'str',
        'error_message': 'str'
    }

    attribute_map = {
        'im_db_id': 'imDbId',
        'name': 'name',
        'description': 'description',
        'items': 'items',
        'name_awards_html': 'nameAwardsHtml',
        'error_message': 'errorMessage'
    }

    def __init__(self, im_db_id=None, name=None, description=None, items=None, name_awards_html=None, error_message=None):  # noqa: E501
        """NameAwardData - a model defined in Swagger"""  # noqa: E501
        self._im_db_id = None
        self._name = None
        self._description = None
        self._items = None
        self._name_awards_html = None
        self._error_message = None
        self.discriminator = None
        if im_db_id is not None:
            self.im_db_id = im_db_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if items is not None:
            self.items = items
        if name_awards_html is not None:
            self.name_awards_html = name_awards_html
        if error_message is not None:
            self.error_message = error_message

    @property
    def im_db_id(self):
        """Gets the im_db_id of this NameAwardData.  # noqa: E501


        :return: The im_db_id of this NameAwardData.  # noqa: E501
        :rtype: str
        """
        return self._im_db_id

    @im_db_id.setter
    def im_db_id(self, im_db_id):
        """Sets the im_db_id of this NameAwardData.


        :param im_db_id: The im_db_id of this NameAwardData.  # noqa: E501
        :type: str
        """

        self._im_db_id = im_db_id

    @property
    def name(self):
        """Gets the name of this NameAwardData.  # noqa: E501


        :return: The name of this NameAwardData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NameAwardData.


        :param name: The name of this NameAwardData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this NameAwardData.  # noqa: E501


        :return: The description of this NameAwardData.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NameAwardData.


        :param description: The description of this NameAwardData.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def items(self):
        """Gets the items of this NameAwardData.  # noqa: E501


        :return: The items of this NameAwardData.  # noqa: E501
        :rtype: list[NameAwardEvent]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this NameAwardData.


        :param items: The items of this NameAwardData.  # noqa: E501
        :type: list[NameAwardEvent]
        """

        self._items = items

    @property
    def name_awards_html(self):
        """Gets the name_awards_html of this NameAwardData.  # noqa: E501


        :return: The name_awards_html of this NameAwardData.  # noqa: E501
        :rtype: str
        """
        return self._name_awards_html

    @name_awards_html.setter
    def name_awards_html(self, name_awards_html):
        """Sets the name_awards_html of this NameAwardData.


        :param name_awards_html: The name_awards_html of this NameAwardData.  # noqa: E501
        :type: str
        """

        self._name_awards_html = name_awards_html

    @property
    def error_message(self):
        """Gets the error_message of this NameAwardData.  # noqa: E501


        :return: The error_message of this NameAwardData.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this NameAwardData.


        :param error_message: The error_message of this NameAwardData.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NameAwardData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NameAwardData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
