# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TrailerData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'im_db_id': 'str',
        'title': 'str',
        'full_title': 'str',
        'type': 'str',
        'year': 'str',
        'video_id': 'str',
        'video_title': 'str',
        'video_description': 'str',
        'thumbnail_url': 'str',
        'upload_date': 'str',
        'link': 'str',
        'link_embed': 'str',
        'error_message': 'str'
    }

    attribute_map = {
        'im_db_id': 'imDbId',
        'title': 'title',
        'full_title': 'fullTitle',
        'type': 'type',
        'year': 'year',
        'video_id': 'videoId',
        'video_title': 'videoTitle',
        'video_description': 'videoDescription',
        'thumbnail_url': 'thumbnailUrl',
        'upload_date': 'uploadDate',
        'link': 'link',
        'link_embed': 'linkEmbed',
        'error_message': 'errorMessage'
    }

    def __init__(self, im_db_id=None, title=None, full_title=None, type=None, year=None, video_id=None, video_title=None, video_description=None, thumbnail_url=None, upload_date=None, link=None, link_embed=None, error_message=None):  # noqa: E501
        """TrailerData - a model defined in Swagger"""  # noqa: E501
        self._im_db_id = None
        self._title = None
        self._full_title = None
        self._type = None
        self._year = None
        self._video_id = None
        self._video_title = None
        self._video_description = None
        self._thumbnail_url = None
        self._upload_date = None
        self._link = None
        self._link_embed = None
        self._error_message = None
        self.discriminator = None
        if im_db_id is not None:
            self.im_db_id = im_db_id
        if title is not None:
            self.title = title
        if full_title is not None:
            self.full_title = full_title
        if type is not None:
            self.type = type
        if year is not None:
            self.year = year
        if video_id is not None:
            self.video_id = video_id
        if video_title is not None:
            self.video_title = video_title
        if video_description is not None:
            self.video_description = video_description
        if thumbnail_url is not None:
            self.thumbnail_url = thumbnail_url
        if upload_date is not None:
            self.upload_date = upload_date
        if link is not None:
            self.link = link
        if link_embed is not None:
            self.link_embed = link_embed
        if error_message is not None:
            self.error_message = error_message

    @property
    def im_db_id(self):
        """Gets the im_db_id of this TrailerData.  # noqa: E501


        :return: The im_db_id of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._im_db_id

    @im_db_id.setter
    def im_db_id(self, im_db_id):
        """Sets the im_db_id of this TrailerData.


        :param im_db_id: The im_db_id of this TrailerData.  # noqa: E501
        :type: str
        """

        self._im_db_id = im_db_id

    @property
    def title(self):
        """Gets the title of this TrailerData.  # noqa: E501


        :return: The title of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this TrailerData.


        :param title: The title of this TrailerData.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def full_title(self):
        """Gets the full_title of this TrailerData.  # noqa: E501


        :return: The full_title of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._full_title

    @full_title.setter
    def full_title(self, full_title):
        """Sets the full_title of this TrailerData.


        :param full_title: The full_title of this TrailerData.  # noqa: E501
        :type: str
        """

        self._full_title = full_title

    @property
    def type(self):
        """Gets the type of this TrailerData.  # noqa: E501


        :return: The type of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TrailerData.


        :param type: The type of this TrailerData.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def year(self):
        """Gets the year of this TrailerData.  # noqa: E501


        :return: The year of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this TrailerData.


        :param year: The year of this TrailerData.  # noqa: E501
        :type: str
        """

        self._year = year

    @property
    def video_id(self):
        """Gets the video_id of this TrailerData.  # noqa: E501


        :return: The video_id of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._video_id

    @video_id.setter
    def video_id(self, video_id):
        """Sets the video_id of this TrailerData.


        :param video_id: The video_id of this TrailerData.  # noqa: E501
        :type: str
        """

        self._video_id = video_id

    @property
    def video_title(self):
        """Gets the video_title of this TrailerData.  # noqa: E501


        :return: The video_title of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._video_title

    @video_title.setter
    def video_title(self, video_title):
        """Sets the video_title of this TrailerData.


        :param video_title: The video_title of this TrailerData.  # noqa: E501
        :type: str
        """

        self._video_title = video_title

    @property
    def video_description(self):
        """Gets the video_description of this TrailerData.  # noqa: E501


        :return: The video_description of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._video_description

    @video_description.setter
    def video_description(self, video_description):
        """Sets the video_description of this TrailerData.


        :param video_description: The video_description of this TrailerData.  # noqa: E501
        :type: str
        """

        self._video_description = video_description

    @property
    def thumbnail_url(self):
        """Gets the thumbnail_url of this TrailerData.  # noqa: E501


        :return: The thumbnail_url of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._thumbnail_url

    @thumbnail_url.setter
    def thumbnail_url(self, thumbnail_url):
        """Sets the thumbnail_url of this TrailerData.


        :param thumbnail_url: The thumbnail_url of this TrailerData.  # noqa: E501
        :type: str
        """

        self._thumbnail_url = thumbnail_url

    @property
    def upload_date(self):
        """Gets the upload_date of this TrailerData.  # noqa: E501


        :return: The upload_date of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._upload_date

    @upload_date.setter
    def upload_date(self, upload_date):
        """Sets the upload_date of this TrailerData.


        :param upload_date: The upload_date of this TrailerData.  # noqa: E501
        :type: str
        """

        self._upload_date = upload_date

    @property
    def link(self):
        """Gets the link of this TrailerData.  # noqa: E501


        :return: The link of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this TrailerData.


        :param link: The link of this TrailerData.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def link_embed(self):
        """Gets the link_embed of this TrailerData.  # noqa: E501


        :return: The link_embed of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._link_embed

    @link_embed.setter
    def link_embed(self, link_embed):
        """Sets the link_embed of this TrailerData.


        :param link_embed: The link_embed of this TrailerData.  # noqa: E501
        :type: str
        """

        self._link_embed = link_embed

    @property
    def error_message(self):
        """Gets the error_message of this TrailerData.  # noqa: E501


        :return: The error_message of this TrailerData.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this TrailerData.


        :param error_message: The error_message of this TrailerData.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrailerData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrailerData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
