# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UsageData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'maximum': 'int',
        'account': 'str',
        'expire_date': 'str',
        'error_message': 'str'
    }

    attribute_map = {
        'count': 'count',
        'maximum': 'maximum',
        'account': 'account',
        'expire_date': 'expireDate',
        'error_message': 'errorMessage'
    }

    def __init__(self, count=None, maximum=None, account=None, expire_date=None, error_message=None):  # noqa: E501
        """UsageData - a model defined in Swagger"""  # noqa: E501
        self._count = None
        self._maximum = None
        self._account = None
        self._expire_date = None
        self._error_message = None
        self.discriminator = None
        if count is not None:
            self.count = count
        if maximum is not None:
            self.maximum = maximum
        if account is not None:
            self.account = account
        if expire_date is not None:
            self.expire_date = expire_date
        if error_message is not None:
            self.error_message = error_message

    @property
    def count(self):
        """Gets the count of this UsageData.  # noqa: E501


        :return: The count of this UsageData.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this UsageData.


        :param count: The count of this UsageData.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def maximum(self):
        """Gets the maximum of this UsageData.  # noqa: E501


        :return: The maximum of this UsageData.  # noqa: E501
        :rtype: int
        """
        return self._maximum

    @maximum.setter
    def maximum(self, maximum):
        """Sets the maximum of this UsageData.


        :param maximum: The maximum of this UsageData.  # noqa: E501
        :type: int
        """

        self._maximum = maximum

    @property
    def account(self):
        """Gets the account of this UsageData.  # noqa: E501


        :return: The account of this UsageData.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this UsageData.


        :param account: The account of this UsageData.  # noqa: E501
        :type: str
        """

        self._account = account

    @property
    def expire_date(self):
        """Gets the expire_date of this UsageData.  # noqa: E501


        :return: The expire_date of this UsageData.  # noqa: E501
        :rtype: str
        """
        return self._expire_date

    @expire_date.setter
    def expire_date(self, expire_date):
        """Sets the expire_date of this UsageData.


        :param expire_date: The expire_date of this UsageData.  # noqa: E501
        :type: str
        """

        self._expire_date = expire_date

    @property
    def error_message(self):
        """Gets the error_message of this UsageData.  # noqa: E501


        :return: The error_message of this UsageData.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this UsageData.


        :param error_message: The error_message of this UsageData.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsageData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsageData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
