# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.8.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserRatingDataDemographicDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rating': 'str',
        'votes': 'str'
    }

    attribute_map = {
        'rating': 'rating',
        'votes': 'votes'
    }

    def __init__(self, rating=None, votes=None):  # noqa: E501
        """UserRatingDataDemographicDetail - a model defined in Swagger"""  # noqa: E501
        self._rating = None
        self._votes = None
        self.discriminator = None
        if rating is not None:
            self.rating = rating
        if votes is not None:
            self.votes = votes

    @property
    def rating(self):
        """Gets the rating of this UserRatingDataDemographicDetail.  # noqa: E501


        :return: The rating of this UserRatingDataDemographicDetail.  # noqa: E501
        :rtype: str
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this UserRatingDataDemographicDetail.


        :param rating: The rating of this UserRatingDataDemographicDetail.  # noqa: E501
        :type: str
        """

        self._rating = rating

    @property
    def votes(self):
        """Gets the votes of this UserRatingDataDemographicDetail.  # noqa: E501


        :return: The votes of this UserRatingDataDemographicDetail.  # noqa: E501
        :rtype: str
        """
        return self._votes

    @votes.setter
    def votes(self, votes):
        """Sets the votes of this UserRatingDataDemographicDetail.


        :param votes: The votes of this UserRatingDataDemographicDetail.  # noqa: E501
        :type: str
        """

        self._votes = votes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserRatingDataDemographicDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserRatingDataDemographicDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
